CREATE LOGIN User1
	WITH PASSWORD = 'Pass@123'

USE books;
CREATE USER User1 FOR LOGIN User1
GO

GRANT ALL ON books TO User1
GRANT SELECT, INSERT, UPDATE, DELETE ON publishers TO User1
GRANT SELECT, INSERT ON book_authors TO User1

REVOKE INSERT ON books FROM User1
REVOKE INSERT, UPDATE, DELETE ON publishers FROM User1